name: Auto Rollback

on:
  workflow_dispatch:

jobs:

  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback Deployment
        run: |
          echo "Rollback Triggered"

      - name: Notify Team
        run: |
          echo "Deployment reverted"